# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Inicio
    url: /#inicio
    weight: 1
  - name: Acerca
    url: '/es/acerca'
    weight: 10
  - name: Documentos
    url: /es/documentos
    weight: 20
  - name: Anuncios
    url: /es/anuncios
    weight: 30
  - name: Reuniones
    url: /es/reuniones
    weight: 40
  - name: Comisiones
    weight: 50
    hasChildren: true
  - parent: Comisiones
    name: Web
    url: es/comisiones/web/
  - parent: Comisiones
    name: Difusión
    url: /es/comisiones/difusion/
  - parent: Comisiones
    name: Juridica
    url: /es/comisiones/juridica/
  - parent: Comisiones
    name: Parlamentaria
    url: /es/comisiones/parlamentaria/
  - parent: Comisiones
    name: Adhesiones
    url: /es/comisiones/adhesiones/