# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: 'RAICYT'
    description: 'Red de Autoridades de Instituciones de Ciencia y Tecnología de Argentina'
    twitter: 'RAICYT_Ar'
  analytics:
    google_analytics: 'G-13H9Q6WGX6'
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo-RAICYT-sol3.svg"
    button:
      enable: false
      text: "Get Started"
      url: "https://hugoblox.com/templates/"
    show_search: true
    show_theme_chooser: true

# Site Features
features:
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/fernan/raicyt'
    content_dir: content
    branch: main
  feedback:
    responses:
      positive: 'Gracias! [Ideas para mejorar?](https://github.com/fernan/raicyt/issues/new)'
      negative: 'Lo lamenta mos. [Decinos como mejorar](https://github.com/fernan/raicyt/issues/new).'

# Site footer
footer:
  copyright:
    notice: '© {year} RAICYT'

# Localization
locale:
  date_format: 'January 2, 2006'
  time_format: '3:04 PM'
  address_format: es-ar

# Extensions
extensions:
  decap_cms:
    branch: main
    publish_mode: editorial_workflow
    #local_backend: true
